[package]
name = "walors"
version = "0.1.0"
edition = "2021"
description = "Pywal implementation for the Ghostty terminal"
keywords = ["pywal", "ghostty"]
categories = ["command-line-utilities"]

[dependencies]
